export const INCIDENCIAS = [
  '1: ENTREVISTA COMPLETA',
  '2: ENTREVISTA INCOMPLETA',
  '3: TEMPORALMENTE AUSENTE',
  '4: INFORMANTE NO CALIFICADO',
  '5: FALTA DE CONTACTO',
  '6: RECHAZO',
  '7: VIVIENDA DESOCUPADA',
  '8: ENTREVISTA FUERA DE PERIODO',
  '9: TRASLADO',
]

export const MAX_POR_UPM = 12
export const INCIDENCIA_TRASLADO = '9: TRASLADO'
export const INCIDENCIA_COMPLETA = '1: ENTREVISTA COMPLETA'

export const TRIMESTRE_ACTUAL = 'III/2026'

export const SEMANA_MIN = 1
export const SEMANA_MAX = 13
export const SEMANA_ANCLA = 5
export const ANCLA_FECHA = new Date(2026, 7, 3)

export const DEPARTAMENTOS = [
  'BENI', 'CHUQUISACA', 'COCHABAMBA', 'LA PAZ', 'ORURO', 'PANDO', 'POTOSÍ', 'SANTA CRUZ', 'TARIJA',
]
